// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pdf} from '../models';
import {context} from '../models';

export function AddWatermark(arg1:string,arg2:string,arg3:string):Promise<pdf.OpResult>;

export function Close(arg1:string):Promise<void>;

export function ExtractPages(arg1:string,arg2:Array<number>,arg3:string):Promise<pdf.OpResult>;

export function ExtractText(arg1:string):Promise<string>;

export function GetState(arg1:string):Promise<pdf.PDFState>;

export function MergeFiles(arg1:Array<string>,arg2:string):Promise<pdf.OpResult>;

export function OpenFile(arg1:string,arg2:string):Promise<Record<string, any>>;

export function Optimize(arg1:string,arg2:string):Promise<pdf.OpResult>;

export function RotatePages(arg1:string,arg2:number,arg3:Array<number>):Promise<pdf.OpResult>;

export function Save(arg1:string):Promise<pdf.OpResult>;

export function SplitFile(arg1:string,arg2:string):Promise<pdf.OpResult>;

export function Startup(arg1:context.Context):Promise<void>;

export function Validate(arg1:string):Promise<pdf.OpResult>;
