// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWatermark(arg1, arg2, arg3) {
  return window['go']['pdf']['Service']['AddWatermark'](arg1, arg2, arg3);
}

export function Close(arg1) {
  return window['go']['pdf']['Service']['Close'](arg1);
}

export function ExtractPages(arg1, arg2, arg3) {
  return window['go']['pdf']['Service']['ExtractPages'](arg1, arg2, arg3);
}

export function ExtractText(arg1) {
  return window['go']['pdf']['Service']['ExtractText'](arg1);
}

export function GetState(arg1) {
  return window['go']['pdf']['Service']['GetState'](arg1);
}

export function MergeFiles(arg1, arg2) {
  return window['go']['pdf']['Service']['MergeFiles'](arg1, arg2);
}

export function OpenFile(arg1, arg2) {
  return window['go']['pdf']['Service']['OpenFile'](arg1, arg2);
}

export function Optimize(arg1, arg2) {
  return window['go']['pdf']['Service']['Optimize'](arg1, arg2);
}

export function RotatePages(arg1, arg2, arg3) {
  return window['go']['pdf']['Service']['RotatePages'](arg1, arg2, arg3);
}

export function Save(arg1) {
  return window['go']['pdf']['Service']['Save'](arg1);
}

export function SplitFile(arg1, arg2) {
  return window['go']['pdf']['Service']['SplitFile'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['pdf']['Service']['Startup'](arg1);
}

export function Validate(arg1) {
  return window['go']['pdf']['Service']['Validate'](arg1);
}
