// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSheet(arg1, arg2) {
  return window['go']['sheets']['Service']['AddSheet'](arg1, arg2);
}

export function Close(arg1) {
  return window['go']['sheets']['Service']['Close'](arg1);
}

export function DeleteRow(arg1, arg2, arg3) {
  return window['go']['sheets']['Service']['DeleteRow'](arg1, arg2, arg3);
}

export function DeleteSheet(arg1, arg2) {
  return window['go']['sheets']['Service']['DeleteSheet'](arg1, arg2);
}

export function ExportCSV(arg1, arg2, arg3) {
  return window['go']['sheets']['Service']['ExportCSV'](arg1, arg2, arg3);
}

export function GetAllRows(arg1, arg2) {
  return window['go']['sheets']['Service']['GetAllRows'](arg1, arg2);
}

export function GetCellRange(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['sheets']['Service']['GetCellRange'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function GetMergedCells(arg1, arg2) {
  return window['go']['sheets']['Service']['GetMergedCells'](arg1, arg2);
}

export function GetState(arg1) {
  return window['go']['sheets']['Service']['GetState'](arg1);
}

export function InsertCol(arg1, arg2, arg3) {
  return window['go']['sheets']['Service']['InsertCol'](arg1, arg2, arg3);
}

export function InsertRow(arg1, arg2, arg3) {
  return window['go']['sheets']['Service']['InsertRow'](arg1, arg2, arg3);
}

export function MergeCells(arg1, arg2, arg3, arg4) {
  return window['go']['sheets']['Service']['MergeCells'](arg1, arg2, arg3, arg4);
}

export function NewWorkbook(arg1) {
  return window['go']['sheets']['Service']['NewWorkbook'](arg1);
}

export function OpenFile(arg1, arg2) {
  return window['go']['sheets']['Service']['OpenFile'](arg1, arg2);
}

export function RenameSheet(arg1, arg2, arg3) {
  return window['go']['sheets']['Service']['RenameSheet'](arg1, arg2, arg3);
}

export function Save(arg1) {
  return window['go']['sheets']['Service']['Save'](arg1);
}

export function SaveAs(arg1, arg2) {
  return window['go']['sheets']['Service']['SaveAs'](arg1, arg2);
}

export function SetAutoFilter(arg1, arg2, arg3) {
  return window['go']['sheets']['Service']['SetAutoFilter'](arg1, arg2, arg3);
}

export function SetCellFormula(arg1, arg2, arg3, arg4) {
  return window['go']['sheets']['Service']['SetCellFormula'](arg1, arg2, arg3, arg4);
}

export function SetCellValue(arg1, arg2, arg3, arg4) {
  return window['go']['sheets']['Service']['SetCellValue'](arg1, arg2, arg3, arg4);
}

export function SetColumnWidth(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['sheets']['Service']['SetColumnWidth'](arg1, arg2, arg3, arg4, arg5);
}

export function SetRowHeight(arg1, arg2, arg3, arg4) {
  return window['go']['sheets']['Service']['SetRowHeight'](arg1, arg2, arg3, arg4);
}

export function Startup(arg1) {
  return window['go']['sheets']['Service']['Startup'](arg1);
}
