// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sheets} from '../models';
import {context} from '../models';

export function AddSheet(arg1:string,arg2:string):Promise<sheets.SaveResult>;

export function Close(arg1:string):Promise<void>;

export function DeleteRow(arg1:string,arg2:string,arg3:number):Promise<sheets.SaveResult>;

export function DeleteSheet(arg1:string,arg2:string):Promise<sheets.SaveResult>;

export function ExportCSV(arg1:string,arg2:string,arg3:string):Promise<sheets.SaveResult>;

export function GetAllRows(arg1:string,arg2:string):Promise<Array<any>>;

export function GetCellRange(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:number):Promise<Array<any>>;

export function GetMergedCells(arg1:string,arg2:string):Promise<Array<sheets.MergeCell>>;

export function GetState(arg1:string):Promise<sheets.WorkbookState>;

export function InsertCol(arg1:string,arg2:string,arg3:number):Promise<sheets.SaveResult>;

export function InsertRow(arg1:string,arg2:string,arg3:number):Promise<sheets.SaveResult>;

export function MergeCells(arg1:string,arg2:string,arg3:string,arg4:string):Promise<sheets.SaveResult>;

export function NewWorkbook(arg1:string):Promise<Record<string, any>>;

export function OpenFile(arg1:string,arg2:string):Promise<Record<string, any>>;

export function RenameSheet(arg1:string,arg2:string,arg3:string):Promise<sheets.SaveResult>;

export function Save(arg1:string):Promise<sheets.SaveResult>;

export function SaveAs(arg1:string,arg2:string):Promise<sheets.SaveResult>;

export function SetAutoFilter(arg1:string,arg2:string,arg3:string):Promise<sheets.SaveResult>;

export function SetCellFormula(arg1:string,arg2:string,arg3:string,arg4:string):Promise<sheets.SaveResult>;

export function SetCellValue(arg1:string,arg2:string,arg3:string,arg4:string):Promise<sheets.SaveResult>;

export function SetColumnWidth(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<sheets.SaveResult>;

export function SetRowHeight(arg1:string,arg2:string,arg3:number,arg4:number):Promise<sheets.SaveResult>;

export function Startup(arg1:context.Context):Promise<void>;
