// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {aiprovider} from '../models';

export function Chat(arg1:context.Context,arg2:aiprovider.ChatRequest):Promise<aiprovider.ChatResponse>;

export function GetSettings():Promise<aiprovider.Settings>;

export function ListModels(arg1:context.Context):Promise<Array<string>>;

export function Stream(arg1:context.Context,arg2:aiprovider.ChatRequest,arg3:any):Promise<void>;

export function UpdateSettings(arg1:aiprovider.Settings):Promise<void>;
