// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Chat(arg1, arg2) {
  return window['go']['aiprovider']['Service']['Chat'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['aiprovider']['Service']['GetSettings']();
}

export function ListModels(arg1) {
  return window['go']['aiprovider']['Service']['ListModels'](arg1);
}

export function Stream(arg1, arg2, arg3) {
  return window['go']['aiprovider']['Service']['Stream'](arg1, arg2, arg3);
}

export function UpdateSettings(arg1) {
  return window['go']['aiprovider']['Service']['UpdateSettings'](arg1);
}
