// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {docs} from '../models';
import {agentcore} from '../models';

export function Close(arg1:string):Promise<void>;

export function DeleteParagraph(arg1:string,arg2:number):Promise<boolean>;

export function ExportHTML(arg1:string,arg2:string):Promise<docs.SaveResult>;

export function ExportText(arg1:string,arg2:string):Promise<docs.SaveResult>;

export function Find(arg1:string,arg2:string):Promise<Array<number>>;

export function FindReplace(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<docs.FindReplaceResult>;

export function GetDocsSkill():Promise<agentcore.Skill>;

export function GetHTMLPreview(arg1:string):Promise<string>;

export function GetParagraphs(arg1:string):Promise<Array<docs.ParaInfo>>;

export function GetState(arg1:string):Promise<docs.DocState>;

export function InsertParagraph(arg1:string,arg2:number,arg3:string):Promise<boolean>;

export function IsDirty(arg1:string):Promise<boolean>;

export function NewBlank(arg1:string):Promise<docs.OpenFileResult>;

export function OpenFile(arg1:string,arg2:string):Promise<docs.OpenFileResult>;

export function Redo(arg1:string):Promise<boolean>;

export function Save(arg1:string):Promise<docs.SaveResult>;

export function SaveAs(arg1:string,arg2:string):Promise<docs.SaveResult>;

export function StartAutosave(arg1:string,arg2:number):Promise<void>;

export function Undo(arg1:string):Promise<boolean>;

export function UpdateParagraph(arg1:string,arg2:number,arg3:string,arg4:boolean,arg5:boolean,arg6:string):Promise<boolean>;
