// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSlide(arg1) {
  return window['go']['slides']['Service']['AddSlide'](arg1);
}

export function Close(arg1) {
  return window['go']['slides']['Service']['Close'](arg1);
}

export function DeleteSlide(arg1, arg2) {
  return window['go']['slides']['Service']['DeleteSlide'](arg1, arg2);
}

export function DuplicateSlide(arg1, arg2) {
  return window['go']['slides']['Service']['DuplicateSlide'](arg1, arg2);
}

export function ExportHTML(arg1, arg2) {
  return window['go']['slides']['Service']['ExportHTML'](arg1, arg2);
}

export function GetSlideData(arg1, arg2) {
  return window['go']['slides']['Service']['GetSlideData'](arg1, arg2);
}

export function GetSlideSVG(arg1, arg2) {
  return window['go']['slides']['Service']['GetSlideSVG'](arg1, arg2);
}

export function GetSlides(arg1) {
  return window['go']['slides']['Service']['GetSlides'](arg1);
}

export function GetSlidesSkill() {
  return window['go']['slides']['Service']['GetSlidesSkill']();
}

export function GetState(arg1) {
  return window['go']['slides']['Service']['GetState'](arg1);
}

export function IsDirty(arg1) {
  return window['go']['slides']['Service']['IsDirty'](arg1);
}

export function MoveSlide(arg1, arg2, arg3) {
  return window['go']['slides']['Service']['MoveSlide'](arg1, arg2, arg3);
}

export function NewBlank(arg1) {
  return window['go']['slides']['Service']['NewBlank'](arg1);
}

export function OpenFile(arg1, arg2) {
  return window['go']['slides']['Service']['OpenFile'](arg1, arg2);
}

export function Redo(arg1) {
  return window['go']['slides']['Service']['Redo'](arg1);
}

export function Save(arg1) {
  return window['go']['slides']['Service']['Save'](arg1);
}

export function SaveAs(arg1, arg2) {
  return window['go']['slides']['Service']['SaveAs'](arg1, arg2);
}

export function Undo(arg1) {
  return window['go']['slides']['Service']['Undo'](arg1);
}

export function UpdateElement(arg1, arg2, arg3, arg4) {
  return window['go']['slides']['Service']['UpdateElement'](arg1, arg2, arg3, arg4);
}
