// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {slides} from '../models';
import {agentcore} from '../models';

export function AddSlide(arg1:string):Promise<slides.SlideInfo>;

export function Close(arg1:string):Promise<void>;

export function DeleteSlide(arg1:string,arg2:number):Promise<boolean>;

export function DuplicateSlide(arg1:string,arg2:number):Promise<slides.SlideInfo>;

export function ExportHTML(arg1:string,arg2:string):Promise<slides.SaveResult>;

export function GetSlideData(arg1:string,arg2:number):Promise<string>;

export function GetSlideSVG(arg1:string,arg2:number):Promise<string>;

export function GetSlides(arg1:string):Promise<Array<slides.SlideInfo>>;

export function GetSlidesSkill():Promise<agentcore.Skill>;

export function GetState(arg1:string):Promise<slides.DeckState>;

export function IsDirty(arg1:string):Promise<boolean>;

export function MoveSlide(arg1:string,arg2:number,arg3:number):Promise<boolean>;

export function NewBlank(arg1:string):Promise<slides.OpenResult>;

export function OpenFile(arg1:string,arg2:string):Promise<slides.OpenResult>;

export function Redo(arg1:string):Promise<boolean>;

export function Save(arg1:string):Promise<slides.SaveResult>;

export function SaveAs(arg1:string,arg2:string):Promise<slides.SaveResult>;

export function Undo(arg1:string):Promise<boolean>;

export function UpdateElement(arg1:string,arg2:number,arg3:string,arg4:string):Promise<boolean>;
