// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {shell} from '../models';
import {context} from '../models';

export function ActivateTab(arg1:string):Promise<void>;

export function CloseTab(arg1:string):Promise<boolean>;

export function GetRecentFiles():Promise<Array<shell.RecentFile>>;

export function GetSettings():Promise<shell.AppSettings>;

export function GetTabs():Promise<Array<shell.TabSummary>>;

export function OnStartup(arg1:context.Context):Promise<void>;

export function OpenTab(arg1:shell.TabKind,arg2:string):Promise<string>;

export function RemoveRecent(arg1:string):Promise<void>;

export function SetTabDirty(arg1:string,arg2:boolean):Promise<void>;

export function SetTabTitle(arg1:string,arg2:string):Promise<void>;

export function ToggleStarred(arg1:string):Promise<void>;

export function UpdateSetting(arg1:string,arg2:any):Promise<void>;
