// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateTab(arg1) {
  return window['go']['shell']['Service']['ActivateTab'](arg1);
}

export function CloseTab(arg1) {
  return window['go']['shell']['Service']['CloseTab'](arg1);
}

export function GetRecentFiles() {
  return window['go']['shell']['Service']['GetRecentFiles']();
}

export function GetSettings() {
  return window['go']['shell']['Service']['GetSettings']();
}

export function GetTabs() {
  return window['go']['shell']['Service']['GetTabs']();
}

export function OnStartup(arg1) {
  return window['go']['shell']['Service']['OnStartup'](arg1);
}

export function OpenTab(arg1, arg2) {
  return window['go']['shell']['Service']['OpenTab'](arg1, arg2);
}

export function RemoveRecent(arg1) {
  return window['go']['shell']['Service']['RemoveRecent'](arg1);
}

export function SetTabDirty(arg1, arg2) {
  return window['go']['shell']['Service']['SetTabDirty'](arg1, arg2);
}

export function SetTabTitle(arg1, arg2) {
  return window['go']['shell']['Service']['SetTabTitle'](arg1, arg2);
}

export function ToggleStarred(arg1) {
  return window['go']['shell']['Service']['ToggleStarred'](arg1);
}

export function UpdateSetting(arg1, arg2) {
  return window['go']['shell']['Service']['UpdateSetting'](arg1, arg2);
}
