// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLang() {
  return window['go']['i18n']['Service']['GetLang']();
}

export function OnLangChange(arg1) {
  return window['go']['i18n']['Service']['OnLangChange'](arg1);
}

export function RegisterBundle(arg1, arg2) {
  return window['go']['i18n']['Service']['RegisterBundle'](arg1, arg2);
}

export function SetLang(arg1) {
  return window['go']['i18n']['Service']['SetLang'](arg1);
}

export function T(arg1, arg2, arg3) {
  return window['go']['i18n']['Service']['T'](arg1, arg2, arg3);
}
