// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {i18n} from '../models';

export function GetLang():Promise<i18n.Lang>;

export function OnLangChange(arg1:any):Promise<void>;

export function RegisterBundle(arg1:string,arg2:i18n.LangDicts):Promise<void>;

export function SetLang(arg1:i18n.Lang):Promise<void>;

export function T(arg1:string,arg2:string,arg3:Array<string>):Promise<string>;
