// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {agentcore} from '../models';
import {context} from '../models';

export function ClearHistory():Promise<void>;

export function GetHistory():Promise<Array<agentcore.Message>>;

export function Run(arg1:context.Context,arg2:string,arg3:agentcore.LoopOptions):Promise<agentcore.RunResult>;
