// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['agentcore']['Loop']['ClearHistory']();
}

export function GetHistory() {
  return window['go']['agentcore']['Loop']['GetHistory']();
}

export function Run(arg1, arg2, arg3) {
  return window['go']['agentcore']['Loop']['Run'](arg1, arg2, arg3);
}
