// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close(arg1) {
  return window['go']['markdown']['Service']['Close'](arg1);
}

export function NewBlank(arg1) {
  return window['go']['markdown']['Service']['NewBlank'](arg1);
}

export function OpenFile(arg1, arg2) {
  return window['go']['markdown']['Service']['OpenFile'](arg1, arg2);
}

export function Save(arg1) {
  return window['go']['markdown']['Service']['Save'](arg1);
}

export function SaveAs(arg1, arg2) {
  return window['go']['markdown']['Service']['SaveAs'](arg1, arg2);
}

export function UpdateContent(arg1, arg2) {
  return window['go']['markdown']['Service']['UpdateContent'](arg1, arg2);
}
