// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Close(arg1:string):Promise<void>;

export function NewBlank(arg1:string):Promise<Record<string, any>>;

export function OpenFile(arg1:string,arg2:string):Promise<Record<string, any>>;

export function Save(arg1:string):Promise<Record<string, any>>;

export function SaveAs(arg1:string,arg2:string):Promise<Record<string, any>>;

export function UpdateContent(arg1:string,arg2:string):Promise<void>;
