// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateProject(arg1) {
  return window['go']['projectstore']['Store']['CreateProject'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['projectstore']['Store']['DeleteProject'](arg1);
}

export function GetProject(arg1) {
  return window['go']['projectstore']['Store']['GetProject'](arg1);
}

export function ListProjects() {
  return window['go']['projectstore']['Store']['ListProjects']();
}

export function LoadChat(arg1, arg2) {
  return window['go']['projectstore']['Store']['LoadChat'](arg1, arg2);
}

export function SaveChat(arg1) {
  return window['go']['projectstore']['Store']['SaveChat'](arg1);
}

export function UpdateProject(arg1, arg2) {
  return window['go']['projectstore']['Store']['UpdateProject'](arg1, arg2);
}
