// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {projectstore} from '../models';

export function CreateProject(arg1:projectstore.ProjectInfo):Promise<projectstore.ProjectInfo>;

export function DeleteProject(arg1:string):Promise<void>;

export function GetProject(arg1:string):Promise<projectstore.ProjectInfo>;

export function ListProjects():Promise<Array<projectstore.ProjectInfo>>;

export function LoadChat(arg1:string,arg2:string):Promise<projectstore.ChatMeta>;

export function SaveChat(arg1:projectstore.ChatMeta):Promise<void>;

export function UpdateProject(arg1:string,arg2:projectstore.ProjectInfo):Promise<void>;
